name: Deploy to EC2

on:
  push:
    branches:
      - main
    paths:
      - 'poller/**'
      - 'primary-backend/**'
      - 'progress-tracker/**'
      - 'player/**'
  pull_request:
    paths:
      - 'poller/**'
      - 'primary-backend/**'
      - 'progress-tracker/**'
      - 'player/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: SSH to EC2
        run: |
          echo "${{ secrets.SSH_KEY }}" > ~/ssh_key
          chmod 700 ~/ssh_key

          ssh -i ~/ssh_key -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_IP }} << 'EOF'
            set -e
            cd /home/ubuntu/video-transcoding-e2e
            git pull

            for dir in poller primary-backend progress-tracker player; do
              cd $dir
              npm install
              npm run build
              cd ..
            done

            pm2 reload pm2.config.json
          EOF
